src/Asp.Net.Core.Examples.KendoGrid/Models/ExampleReportViewModel.cs
namespace Asp.Net.Core.Examples.KendoGrid.Models
{
	/// <summary>
	/// Представляет пример отчета.
	/// </summary>
	/// <seealso cref="ReportViewModelBase" />
	public class ExampleReportViewModel : ReportViewModelBase
	{
		#region Properties
		public string Code { get; set; }

		public string Name { get; set; }
		#endregion
	}
}

src/Asp.Net.Core.Examples.KendoGrid/Models/ExampleViewModelGridBuilder.cs
using Asp.Net.Core.Examples.KendoGrid.Infrastructure.Components.Grid.Abstractions;
using Kendo.Mvc.UI;
using Kendo.Mvc.UI.Fluent;

namespace Asp.Net.Core.Examples.KendoGrid.Models
{
	/// <summary>
	/// Представляет реализацию осуществляющую создание элемента <see cref="Grid{T}" />.
	/// </summary>
	/// <seealso cref="GridBuilderBase{T}" />
	public class ExampleViewModelGridBuilder : GridBuilderBase<ExampleReportViewModel>
	{
		#region Overrided
		/// <inheritdoc />
		protected override void ConfigureColumns(GridColumnFactory<ExampleReportViewModel> columnFactory)
		{
			// Пример конфигурации для ExampleReportViewModel.

			columnFactory.Bound(model => model.Name)
						 .Title("Имя");
			columnFactory.Bound(model => model.Code)
						 .Title("Код");
		}
		#endregion
	}
}

src/Asp.Net.Core.Examples.KendoGrid/Models/ReportViewModelBase.cs
namespace Asp.Net.Core.Examples.KendoGrid.Models
{
	/// <summary>
	/// Представляет базовую реализацию Отчета.
	/// </summary>
	public abstract class ReportViewModelBase
	{
	}
}

src/Asp.Net.Core.Examples.KendoGrid/Controllers/HomeController.cs
using System.Collections.Generic;
using Asp.Net.Core.Examples.KendoGrid.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;

namespace Asp.Net.Core.Examples.KendoGrid.Controllers
{
	public class HomeController : Controller
	{
		#region Public
		public IActionResult GetData([DataSourceRequest] DataSourceRequest request)
		{
			var lst = new List<ExampleReportViewModel>
			{
				new ExampleReportViewModel
				{
					Name = "Name 1",
					Code = "Code 1"
				},
				new ExampleReportViewModel
				{
					Name = "Name 2",
					Code = "Code 2"
				}
			};
			return Json(lst.ToDataSourceResult(request));
		}

		public IActionResult Index() => View();
		#endregion
	}
}

src/Asp.Net.Core.Examples.KendoGrid/Infrastructure/Components/Grid/GridViewComponent.cs
using System;
using Asp.Net.Core.Examples.KendoGrid.Infrastructure.Components.Grid.Abstractions;
using JetBrains.Annotations;
using Kendo.Mvc.UI.Fluent;
using Microsoft.AspNetCore.Mvc;

namespace Asp.Net.Core.Examples.KendoGrid.Infrastructure.Components.Grid
{
	/// <summary>
	/// Представляет компонент Таблица.
	/// </summary>
	/// <seealso cref="ViewComponent" />
	public class GridViewComponent : ViewComponent
	{
		#region Data
		#region Fields
		private readonly IGridBuilderResolver _gridBuilderResolver;
		#endregion
		#endregion

		#region .ctor
		/// <summary>
		/// Инициализирует новый экземпляр класса <see cref="GridViewComponent" />.
		/// </summary>
		/// <param name="gridBuilderResolver">
		/// Реализация компонента, используемого для динамического поиска соответствующего
		/// <see cref="GridBuilder{T}" /> для типа T.
		/// </param>
		/// <exception cref="ArgumentNullException">Если <paramref name="gridBuilderResolver" /> равен null.</exception>
		public GridViewComponent([NotNull] IGridBuilderResolver gridBuilderResolver) => _gridBuilderResolver = gridBuilderResolver ?? throw new ArgumentNullException(nameof(gridBuilderResolver));
		#endregion

		#region Public
		/// <summary>
		/// Вызывается при визуализации компонента из представления.
		/// </summary>
		/// <param name="type">Тип данных, для которого необходимо построить таблицу.</param>
		/// <exception cref="ArgumentNullException">Если <paramref name="type" /> равен null.</exception>
		/// <returns>Результат для отображения представлением.</returns>
		public IViewComponentResult Invoke([NotNull] Type type)
		{
			if (type == null)
			{
				throw new ArgumentNullException(nameof(type));
			}

			var gridBuilderFunc = _gridBuilderResolver.Resolve(type);
			return View(gridBuilderFunc);
		}
		#endregion
	}
}

src/Asp.Net.Core.Examples.KendoGrid/Views/Home/Index.cshtml
@using Asp.Net.Core.Examples.KendoGrid.Models
@model object

@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<title>Kendo Grid</title>
	<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.3.1023/styles/kendo.bootstrap-v4.min.css"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="https://kendo.cdn.telerik.com/2019.3.1023/js/kendo.all.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2019.3.1023/js/kendo.aspnetmvc.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<div>
	@* Хардкод в качестве примера. *@
	@* На практике тип отчета будет каким-то образом определяться динамически и передаваться в представление. *@
	@await Component.InvokeAsync("Grid", new
	{
		Type = typeof(ExampleReportViewModel)
	})
</div>
</body>
</html>

src/Asp.Net.Core.Examples.KendoGrid/Views/Shared/Components/Grid/Default.cshtml
@using Kendo.Mvc.UI
@{
	var gridBuilderFunc = Model;
	var widgetFactory = Html.Kendo();

	var grid = gridBuilderFunc(widgetFactory);
	@(grid)
}